export const family = {
  'x.tatia': {
    firstName: 'x',
    lastName: 'tatia',
    nickname: 'x',
    gender: 'male',
    photo: 'https://picsum.photos/200',
    dob: '01/01/1920',
    dod: '01/01/2000',
    events: [],
    partner: {
      partnerOf: 'x.tatia',
      marriage_data: '01/01/1945',
      firstName: 'y',
      lastName: 'tatia',
      nickname: 'y',
      gender: 'female',
      photo: 'https://picsum.photos/200',
      dob: '01/01/1925',
      dod: '01/01/2020',
      events: [],
      children: ['prithviraj.tatia', 'prakash.tatia']
    }
  },
  'prithviraj.tatia': {
    firstName: 'prithiviraj',
    lastName: 'tatia',
    nickname: 'pimu',
    gender: 'male',
    photo: 'https://picsum.photos/200',
    dob: '01/01/1950',
    dod: '01/01/2011',
    events: [],
    partner: {
      partnerOf: 'prithviraj.tatia',
      marriage_data: '01/01/1945',
      firstName: 'shashi',
      lastName: 'tatia',
      nickname: 'shashi',
      gender: 'female',
      photo: 'https://picsum.photos/200',
      dob: '01/01/1953',
      dod: '01/01/2011',
      events: [],
      children: ['rakesh.tatia', 'chiku.tatia']
    }
  },
  'prakash.tatia': {
    firstName: 'prakash',
    lastName: 'tatia',
    nickname: 'daddy',
    gender: 'male',
    photo: 'https://picsum.photos/200',
    dob: '01/01/1955',
    dod: '',
    events: [],
    partner: {
      partnerOf: 'prakash.tatia',
      marriage_data: '01/01/1975',
      firstName: 'chandu',
      lastName: 'tatia',
      nickname: 'chandu',
      gender: 'female',
      photo: 'https://picsum.photos/200',
      dob: '01/01/1958',
      dod: '',
      events: [],
      children: ['abhishek.tatia', 'anu.tatia', 'sharad.tatia']
    }
  },
  'rakesh.tatia': {
    firstName: 'rakesh',
    lastName: 'tatia',
    nickname: 'riku',
    gender: 'male',
    photo: 'https://picsum.photos/200',
    dob: '06/20/1972',
    dod: '',
    events: [],
    partner: {
      partnerOf: 'rakesh.tatia',
      marriage_data: '12/14/1997',
      firstName: 'prerna',
      lastName: 'tatia',
      nickname: 'monu',
      gender: 'female',
      photo: 'https://picsum.photos/200',
      dob: '10/05/1974',
      dod: '',
      events: [],
      children: ['rishabh.tatia']
    }
  },
  'abhishek.tatia': {
    firstName: 'abhishek',
    lastName: 'tatia',
    nickname: 'betu',
    gender: 'male',
    photo: 'https://picsum.photos/200',
    dob: '06/20/1972',
    dod: '',
    events: [],
    partner: {
      partnerOf: 'abhishek.tatia',
      marriage_data: '12/14/1997',
      firstName: 'anjali',
      lastName: 'tatia',
      nickname: 'anjali',
      gender: 'female',
      photo: 'https://picsum.photos/200',
      dob: '10/05/1974',
      dod: '',
      events: [],
      children: ['arihant.tatia', 'arham.tatia']
    }
  },
  'anu.tatia': {
    firstName: 'anu',
    lastName: 'tatia',
    nickname: 'anu',
    gender: 'female',
    photo: 'https://picsum.photos/200',
    dob: '06/20/1972',
    dod: '',
    events: [],
    partner: {
      partnerOf: 'anu.tatia',
      marriage_data: '12/14/1997',
      firstName: 'saurav',
      lastName: 'tatia',
      nickname: 'saurav',
      gender: 'male',
      photo: 'https://picsum.photos/200',
      dob: '10/05/1974',
      dod: '',
      events: [],
      children: ['anvi.tatia']
    }
  },
  'sharad.tatia': {
    firstName: 'sharad',
    lastName: 'tatia',
    nickname: 'sharad',
    gender: 'male',
    photo: 'https://picsum.photos/200',
    dob: '06/20/1972',
    dod: '',
    events: [],
    partner: {
      partnerOf: 'sharad.tatia',
      marriage_data: '12/14/1997',
      firstName: 'richa',
      lastName: 'tatia',
      nickname: 'richa',
      gender: 'female',
      photo: 'https://picsum.photos/200',
      dob: '10/05/1974',
      dod: '',
      events: [],
      children: ['mishti.tatia']
    }
  },
  'chiku.tatia': {
    firstName: 'chiku',
    lastName: 'tatia',
    nickname: 'chiku',
    gender: 'male',
    photo: 'https://picsum.photos/200',
    dob: '04/03/1974',
    dod: '01/01/1992',
    events: [],
    partner: null
  },
  'rishabh.tatia': {
    firstName: 'rishabh',
    lastName: 'tatia',
    nickname: 'rishu',
    gender: 'male',
    photo: 'https://picsum.photos/200',
    dob: '01/03/2001',
    dod: '',
    events: [{
      date: '05/14/2022',
      title: 'Graduated from Texas A&M University',
    }],
    partner: null
  },
  'arihant.tatia': {
    firstName: 'arihant',
    lastName: 'tatia',
    nickname: 'arihant',
    gender: 'male',
    photo: 'https://picsum.photos/200',
    dob: '01/03/2001',
    dod: '',
    events: [],
    partner: null
  },
  'arham.tatia': {
    firstName: 'arham',
    lastName: 'tatia',
    nickname: 'arham',
    gender: 'male',
    photo: 'https://picsum.photos/200',
    dob: '01/03/2001',
    dod: '',
    events: [],
    partner: null
  },
  'anvi.tatia': {
    firstName: 'anvi',
    lastName: 'tatia',
    nickname: 'anvi',
    gender: 'female',
    photo: 'https://picsum.photos/200',
    dob: '01/03/2001',
    dod: '',
    events: [],
    partner: null
  },
  'mishti.tatia': {
    firstName: 'mishti',
    lastName: 'tatia',
    nickname: 'mishti',
    gender: 'female',
    photo: 'https://picsum.photos/200',
    dob: '01/03/2001',
    dod: '',
    events: [],
    partner: null
  }
}