export const family = {
  'jaswant.tatia': {
    id: 'jaswant.tatia',
    firstName: 'jaswant',
    lastName: 'tatia',
    parentId: null,
    nickname: 'jaswant',
    gender: 'male',
    photo: '/img/guy-1.png',
    dob: '01/01/1920',
    dod: '01/01/1984',
    events: [],
    partner: {
      id: 'sardar.tatia',
      partnerOf: 'jaswant.tatia',
      marriage_date: '25/01/1958',
      firstName: 'sardar',
      lastName: 'kanwar',
      parentId: null,
      nickname: 'sardar',
      gender: 'female',
      photo: '/img/sardar.tatia.jpeg',
      dob: '01/01/1928',
      dod: '03/19/2018',
      events: [],
      children: ['dalpat.tatia', 'prithvi.tatia', 'vimala.bhansali', 'prakash.tatia', 'rajesh.tatia', 'ashok.tatia', 'umesh.tatia']
    }
  },
  'dalpat.tatia': {
    id: 'dalpat.tatia',
    firstName: 'dalpat Raj',
    lastName: 'tatia',
    parentId: 'jaswant.tatia',
    nickname: 'dalpat',
    gender: 'male',
    photo: '/img/guy-1.png',
    dob: '01/01/1944',
    dod: '03/04/2004',
    events: [],
    partner: {
      id: 'kanchan.tatia',
      partnerOf: 'dalpat.tatia',
      marriage_date: '01/01/1945',
      firstName: 'kanchan',
      lastName: 'tatia',
      parentId: null,
      nickname: 'kanchan',
      gender: 'female',
      photo: '/img/girl-1.png',
      dob: '01/01/1944',
      dod: '03/04/2004',
      events: [],
      children: ['reena.kothari', 'nikky.tater', 'surbhi.kumbhat']
    }
  },
  'prithvi.tatia': {
    id: 'prithvi.tatia',
    firstName: 'prithvi Raj',
    lastName: 'tatia',
    parentId: 'jaswant.tatia',
    nickname: 'pimu',
    gender: 'male',
    photo: '/img/guy-1.png',
    dob: '09/29/1947',
    dod: '05/13/2013',
    events: [],
    partner: {
      id: 'shashi.tatia',
      partnerOf: 'prithvi.tatia',
      marriage_date: '12/11/1970',
      firstName: 'shashi',
      lastName: 'tatia',
      parentId: null,
      nickname: 'shashi',
      gender: 'female',
      photo: '/img/girl-1.png',
      dob: '03/27/1950',
      dod: '11/19/2012',
      events: [],
      children: ['rakesh.tatia', 'sumeet.tatia']
    }
  },
  'vimala.bhansali': {
    id: 'vimala.bhansali',
    firstName: 'vimala',
    lastName: 'bhansali',
    parentId: 'jaswant.tatia',
    nickname: 'vimala',
    gender: 'female',
    photo: '/img/girl-1.png',
    dob: '10/04/1949',
    dod: '',
    events: [],
    partner: {
      id: 'jagdish.bhansali',
      partnerOf: 'vimala.bhansali',
      marriage_date: '12/06/1969',
      firstName: 'jagdish',
      lastName: 'bhansali',
      parentId: null,
      nickname: 'jagdish',
      gender: 'male',
      photo: '/img/guy-1.png',
      dob: '10/23/1944',
      dod: '',
      events: [],
      children: ['piyush.bhansali', 'priyanka.singhvi']
    }
  },
  'prakash.tatia': {
    id: 'prakash.tatia',
    firstName: 'prakash',
    lastName: 'tatia',
    parentId: 'jaswant.tatia',
    nickname: 'daddy',
    gender: 'male',
    photo: '/img/guy-1.png',
    dob: '08/11/1950',
    dod: '',
    events: [],
    partner: {
      id: 'chandrakala.tatia',
      partnerOf: 'prakash.tatia',
      marriage_date: '01/25/1977',
      firstName: 'chandrakala',
      lastName: 'tatia',
      parentId: null,
      nickname: 'chandu',
      gender: 'female',
      photo: '/img/girl-1.png',
      dob: '12/18/1955',
      dod: '',
      events: [],
      children: ['abhishek.tatia', 'aayushi.bhandari', 'amit.tatia']
    }
  },
  'umesh.tatia': {
    id: 'umesh.tatia',
    firstName: 'umesh',
    lastName: 'tatia',
    parentId: 'jaswant.tatia',
    nickname: 'tepu',
    gender: 'male',
    photo: '/img/umesh.tatia.jpeg',
    dob: '02/04/1960',
    dod: '',
    events: [],
    partner: {
      id: 'renu.tatia',
      partnerOf: 'umesh.tatia',
      marriage_date: '05/19/1986',
      firstName: 'renu',
      lastName: 'tatia',
      parentId: null,
      nickname: 'renu',
      gender: 'female',
      photo: '/img/renu.tatia.jpeg',
      dob: '02/15/1965',
      dod: '',
      events: [],
      children: ['rini.jain', 'monika.kachawa']
    }
  },
  'ashok.tatia': {
    id: 'ashok.tatia',
    firstName: 'ashok',
    lastName: 'tatia',
    parentId: 'jaswant.tatia',
    nickname: 'sathu',
    gender: 'male',
    photo: '/img/ashok.tatia.jpeg',
    dob: '05/28/1957',
    dod: '',
    events: [],
    partner: {
      id: 'neelu.tatia',
      partnerOf: 'ashok.tatia',
      marriage_date: '02/18/1984',
      firstName: 'neelu',
      lastName: 'tatia',
      parentId: null,
      nickname: 'neelu',
      gender: 'female',
      photo: '/img/neelu.tatia.jpeg',
      dob: '03/29/1960',
      dod: '',
      events: [],
      children: ['swati.jain', 'megha.tatia']
    }
  },
  'rajesh.tatia': {
    id: 'rajesh.tatia',
    firstName: 'rajesh',
    lastName: 'tatia',
    parentId: 'jaswant.tatia',
    nickname: 'raju',
    gender: 'male',
    photo: '/img/guy-1.png',
    dob: '01/20/1954',
    dod: '',
    events: [],
    partner: {
      id: 'asha.tatia',
      partnerOf: 'rajesh.tatia',
      marriage_date: '01/29/1980',
      firstName: 'asha',
      lastName: 'tatia',
      parentId: null,
      nickname: 'asha',
      gender: 'female',
      photo: '/img/asha.tatia.jpeg',
      dob: '09/24/1959',
      dod: '',
      events: [],
      children: ['akhil.tatia', 'nikhil.tatia']
    }
  },
  'rini.jain': {
    id: 'rini.jain',
    firstName: 'rini',
    lastName: 'jain',
    parentId: 'umesh.tatia',
    nickname: 'bolly',
    gender: 'female',
    photo: '/img/rini.jain.jpeg',
    dob: '12/23/1987',
    dod: '',
    events: [],
    partner: {
      id: 'piyush.jain',
      partnerOf: 'rini.jain',
      marriage_date: '12/10/2013',
      firstName: 'piyush',
      lastName: 'jain',
      parentId: null,
      nickname: 'piyush',
      gender: 'male',
      photo: '/img/guy-1.png',
      dob: '02/01/1984',
      dod: '',
      events: [],
      children: ['prabhir.jain']
    }
  },
  'monika.kachawa': {
    id: 'monika.kachawa',
    firstName: 'monika',
    lastName: 'kachawa',
    parentId: 'umesh.tatia',
    nickname: 'bolly',
    gender: 'female',
    photo: '/img/monika.kachawa.jpeg',
    dob: '11/28/1991',
    dod: '',
    events: [],
    partner: {
      id: 'varun.kachawa',
      partnerOf: 'monika.kachawa',
      marriage_date: '02/08/2015',
      firstName: 'varun',
      lastName: 'kachawa',
      parentId: null,
      nickname: 'varun',
      gender: 'male',
      photo: '/img/varun.kachawa.jpeg',
      dob: '11/21/1988',
      dod: '',
      events: [],
      children: []
    }
  },
  'swati.jain': {
    id: 'swati.jain',
    firstName: 'swati',
    lastName: 'jain',
    parentId: 'ashok.tatia',
    nickname: 'archi',
    gender: 'female',
    photo: '/img/swati.jain.jpeg',
    dob: '01/09/1985',
    dod: '',
    events: [],
    partner: {
      id: 'vishal.jain',
      partnerOf: 'swati.jain',
      marriage_date: '04/13/2012',
      firstName: 'vishal',
      lastName: 'jain',
      parentId: null,
      nickname: 'vishal',
      gender: 'male',
      photo: '/img/vishal.jain.jpeg',
      dob: '07/06/1982',
      dod: '',
      events: [],
      children: ['advay.jain']
    }
  },
  'megha.tatia': {
    id: 'megha.tatia',
    firstName: 'megha',
    lastName: 'tatia',
    parentId: 'ashok.tatia',
    nickname: 'guddu',
    gender: 'female',
    photo: '/img/megha.tatia.jpeg',
    dob: '02/10/1988',
    dod: '',
    events: [],
    partner: {
      id: 'nitin.tatia',
      partnerOf: 'megha.tatia',
      marriage_date: '12/24/2020',
      firstName: 'nitin',
      lastName: 'tatia',
      parentId: null,
      nickname: 'nitin',
      gender: 'male',
      photo: '/img/guy-1.png',
      dob: '06/22/1984',
      dod: '',
      events: [],
      children: []
    }
  },
  'akhil.tatia': {
    id: 'akhil.tatia',
    firstName: 'akhil',
    lastName: 'tatia',
    parentId: 'rajesh.tatia',
    nickname: 'akhil',
    gender: 'male',
    photo: '/img/akhil.tatia.jpeg',
    dob: '01/18/1983',
    dod: '',
    events: [],
    partner: {
      id: 'kritika.tatia',
      partnerOf: 'akhil.tatia',
      marriage_date: '12/22/2011',
      firstName: 'kritika',
      lastName: 'tatia',
      parentId: null,
      nickname: 'kritika',
      gender: 'female',
      photo: '/img/girl-1.png',
      dob: '10/13/1986',
      dod: '',
      events: [],
      children: ['akshat.tatia', 'navya.tatia']
    }
  },
  'nikhil.tatia': {
    id: 'nikhil.tatia',
    firstName: 'nikhil',
    lastName: 'tatia',
    parentId: 'rajesh.tatia',
    nickname: 'nikhil',
    gender: 'male',
    photo: '/img/nikhil.tatia.jpeg',
    dob: '12/24/1985',
    dod: '',
    events: [],
    partner: {
      id: 'ankita.tatia',
      partnerOf: 'nikhil.tatia',
      marriage_date: '12/23/2012',
      firstName: 'ankita',
      lastName: 'tatia',
      parentId: null,
      nickname: 'ankita',
      gender: 'female',
      photo: '/img/ankita.tatia.jpeg',
      dob: '11/29/1986',
      dod: '',
      events: [],
      children: ['parth.tatia']
    }
  },
  'rakesh.tatia': {
    id: 'rakesh.tatia',
    firstName: 'rakesh',
    lastName: 'tatia',
    parentId: 'prithvi.tatia',
    nickname: 'riku',
    gender: 'male',
    photo: '/img/guy-1.png',
    dob: '06/20/1972',
    dod: '',
    events: [],
    partner: {
      id: 'prerna.tatia',
      partnerOf: 'rakesh.tatia',
      marriage_date: '12/14/1997',
      firstName: 'prerna',
      lastName: 'tatia',
      parentId: null,
      nickname: 'prerna',
      gender: 'female',
      photo: '/img/girl-1.png',
      dob: '10/05/1974',
      dod: '',
      events: [],
      children: ['rishabh.tatia']
    }
  },
  'piyush.bhansali': {
    id: 'piyush.bhansali',
    firstName: 'piyush',
    lastName: 'bhansali',
    parentId: 'vimala.bhansali',
    nickname: 'prince',
    gender: 'male',
    photo: '/img/guy-1.png',
    dob: '06/24/1971',
    dod: '',
    events: [],
    partner: {
      id: 'vanita.bhansali',
      partnerOf: 'piyush.bhansali',
      marriage_date: '02/06/1998',
      firstName: 'vanita',
      lastName: 'bhansali',
      parentId: null,
      nickname: 'vanita',
      gender: 'female',
      photo: '/img/girl-1.png',
      dob: '04/30/1973',
      dod: '',
      events: [],
      children: ['priyanshi.bhansali', 'mahek.bhansali']
    }
  },
  'priyanka.singhvi': {
    id: 'priyanka.singhvi',
    firstName: 'priyanka',
    lastName: 'singhvi',
    parentId: 'vimala.bhansali',
    nickname: 'pinky',
    gender: 'female',
    photo: '/img/priyanka.singhvi.jpeg',
    dob: '03/25/1979',
    dod: '',
    events: [],
    partner: {
      id: 'rupesh.singhvi',
      partnerOf: 'priyanka.singhvi',
      marriage_date: '12/09/2001',
      firstName: 'rupesh',
      lastName: 'singhvi',
      parentId: null,
      nickname: 'rupesh',
      gender: 'male',
      photo: '/img/guy-1.png',
      dob: '06/23/1975',
      dod: '',
      events: [],
      children: ['neelay.singhvi', 'rakshiti.singhvi']
    }
  },
  'reena.kothari': {
    id: 'reena.kothari',
    firstName: 'reena',
    lastName: 'kothari',
    parentId: 'dalpat.tatia',
    nickname: 'reena',
    gender: 'female',
    photo: '/img/girl-1.png',
    dob: '01/08/1971',
    dod: '',
    events: [],
    partner: {
      id: 'nirmal.kothari',
      partnerOf: 'reena.kothari',
      marriage_date: '05/28/1990',
      firstName: 'nirmal',
      lastName: 'kothari',
      parentId: null,
      nickname: 'nirmal',
      gender: 'male',
      photo: '/img/guy-1.png',
      dob: '12/03/1965',
      dod: '',
      events: [],
      children: ['juhi.mehta', 'shaily.kothari', 'pragya.kothari']
    }
  },
  'nikky.tater': {
    id: 'nikky.tater',
    firstName: 'nikki',
    lastName: 'tater',
    parentId: 'dalpat.tatia',
    nickname: 'nikki',
    gender: 'female',
    photo: '/img/girl-1.png',
    dob: '01/03/1975',
    dod: '',
    events: [],
    partner: {
      id: 'sanjay.tater',
      partnerOf: 'nikky.tater',
      marriage_date: '11/10/1995',
      firstName: 'sanjay',
      lastName: 'tater',
      parentId: null,
      nickname: 'sanjay',
      gender: 'male',
      photo: '/img/sanjay.tater.jpeg',
      dob: '11/11/1970',
      dod: '',
      events: [],
      children: ['isha.tater', 'aryan.tater']
    }
  },
  'surbhi.kumbhat': {
    id: 'surbhi.kumbhat',
    firstName: 'surbhi',
    lastName: 'kumbhat',
    parentId: 'dalpat.tatia',
    nickname: 'surbhi',
    gender: 'female',
    photo: '/img/girl-1.png',
    dob: '09/01/1977',
    dod: '',
    events: [],
    partner: {
      id: 'neeraj.kumbhat',
      partnerOf: 'surbhi.kumbhat',
      marriage_date: '11/10/1995',
      firstName: 'neeraj',
      lastName: 'kumbhat',
      parentId: null,
      nickname: 'neeraj',
      gender: 'male',
      photo: '/img/guy-1.png',
      dob: '03/13/1971',
      dod: '',
      events: [],
      children: ['ritika.kumbhat', 'kavya.kumbhat']
    }
  },
  'abhishek.tatia': {
    id: 'abhishek.tatia',
    firstName: 'abhishek',
    lastName: 'tatia',
    parentId: 'prakash.tatia',
    nickname: 'betu',
    gender: 'male',
    photo: '/img/abhishek.tatia.jpeg',
    dob: '04/02/1979',
    dod: '',
    events: [],
    partner: {
      id: 'anjali.tatia',
      partnerOf: 'abhishek.tatia',
      marriage_date: '11/28/2006',
      firstName: 'anjali',
      lastName: 'tatia',
      parentId: null,
      nickname: 'anjali',
      gender: 'female',
      photo: '/img/anjali.tatia.jpeg',
      dob: '01/01/1982',
      dod: '',
      events: [],
      children: ['arihant.tatia', 'arham.tatia']
    }
  },
  'aayushi.bhandari': {
    id: 'aayushi.bhandari',
    firstName: 'aayushi',
    lastName: 'bhandari',
    parentId: 'prakash.tatia',
    nickname: 'anu',
    gender: 'female',
    photo: '/img/aayushi.bhandari.jpeg',
    dob: '12/03/1983',
    dod: '',
    events: [],
    partner: {
      id: 'saurabh.bhandari',
      partnerOf: 'aayushi.bhandari',
      marriage_date: '11/02/2008',
      firstName: 'saurabh',
      lastName: 'bhandari',
      parentId: null,
      nickname: 'saurabh',
      gender: 'male',
      photo: '/img/saurabh.bhandari.jpeg',
      dob: '07/07/1983',
      dod: '',
      events: [],
      children: ['anvi.bhandari']
    }
  },
  'amit.tatia': {
    id: 'amit.tatia',
    firstName: 'amit',
    lastName: 'tatia',
    parentId: 'prakash.tatia',
    nickname: 'sharad',
    gender: 'male',
    photo: '/img/amit.tatia.jpeg',
    dob: '10/01/1982',
    dod: '',
    events: [],
    partner: {
      id: 'richa.tatia',
      partnerOf: 'amit.tatia',
      marriage_date: '12/25/2011',
      firstName: 'richa',
      lastName: 'tatia',
      parentId: null,
      nickname: 'richa',
      gender: 'female',
      photo: '/img/richa.tatia.jpeg',
      dob: '10/05/1986',
      dod: '',
      events: [],
      children: ['mishti.tatia', 'shiney.tatia']
    }
  },
  'sumeet.tatia': {
    id: 'sumeet.tatia',
    firstName: 'sumeet',
    lastName: 'tatia',
    parentId: 'prithvi.tatia',
    nickname: 'chiku',
    gender: 'male',
    photo: '/img/guy-1.png',
    dob: '09/30/1975',
    dod: '08/13/1995',
    events: [],
    partner: null
  },
  'juhi.mehta': {
    id: 'juhi.mehta',
    firstName: 'juhi',
    lastName: 'mehta',
    parentId: 'reena.kothari',
    nickname: 'juhi',
    gender: 'female',
    photo: '/img/juhi.mehta.jpeg',
    dob: '11/02/1992',
    dod: '',
    events: [],
    partner: {
      id: 'sridhar.mehta',
      partnerOf: 'juhi.mehta',
      marriage_date: '02/06/2018',
      firstName: 'sridhar',
      lastName: 'mehta',
      parentId: null,
      nickname: 'sridhar',
      gender: 'male',
      photo: '/img/guy-1.png',
      dob: '10/05/1990',
      dod: '',
      events: [],
      children: []
    }
  },
  'shaily.kothari': {
    id: 'shaily.kothari',
    firstName: 'sonu',
    lastName: 'kothari',
    parentId: 'reena.kothari',
    nickname: 'sonu',
    gender: 'female',
    photo: '/img/shaily.kothari.jpeg',
    dob: '05/29/1997',
    dod: '',
    events: [],
    partner: null
  },
  'pragya.kothari': {
    id: 'pragya.kothari',
    firstName: 'pragya',
    lastName: 'kothari',
    parentId: 'reena.kothari',
    nickname: 'pragy',
    gender: 'male',
    photo: '/img/pragya.kothari.jpeg',
    dob: '10/15/2004',
    dod: '',
    events: [],
    partner: null
  },
  'neelay.singhvi': {
    id: 'neelay.singhvi',
    firstName: 'neelay',
    lastName: 'singhvi',
    parentId: 'priyanka.singhvi',
    nickname: 'neelay',
    gender: 'male',
    photo: '/img/guy-1.png',
    dob: '09/27/2002',
    dod: '',
    events: [],
    partner: null
  },
  'rakshiti.singhvi': {
    id: 'rakshiti.singhvi',
    firstName: 'rakshiti',
    lastName: 'singhvi',
    parentId: 'priyanka.singhvi',
    nickname: 'bebo',
    gender: 'female',
    photo: '/img/rakshiti.singhvi.jpeg',
    dob: '12/21/2007',
    dod: '',
    events: [],
    partner: null
  },
  'priyanshi.bhansali': {
    id: 'priyanshi.bhansali',
    firstName: 'priyanshi',
    lastName: 'bhansali',
    parentId: 'piyush.bhansali',
    nickname: 'priyanshi',
    gender: 'female',
    photo: '/img/girl-1.png',
    dob: '02/15/1999',
    dod: '',
    events: [],
    partner: null
  },
  'mahek.bhansali': {
    id: 'mahek.bhansali',
    firstName: 'mahek',
    lastName: 'bhansali',
    parentId: 'piyush.bhansali',
    nickname: 'mahek',
    gender: 'female',
    photo: '/img/girl-1.png',
    dob: '11/17/2003',
    dod: '',
    events: [],
    partner: null
  },
  'isha.tater': {
    id: 'isha.tater',
    firstName: 'isha',
    lastName: 'tater',
    parentId: 'nikky.tater',
    nickname: 'guddu',
    gender: 'female',
    photo: '/img/girl-1.png',
    dob: '04/25/1998',
    dod: '',
    events: [],
    partner: null
  },
  'aryan.tater': {
    id: 'aryan.tater',
    firstName: 'aryan',
    lastName: 'tater',
    parentId: 'nikky.tater',
    nickname: 'aru',
    gender: 'male',
    photo: '/img/aryan.tater.jpeg',
    dob: '10/30/2000',
    dod: '',
    events: [],
    partner: null
  },
  'ritika.kumbhat': {
    id: 'ritika.kumbhat',
    firstName: 'ritika',
    lastName: 'kumbhat',
    parentId: 'surbhi.kumbhat',
    nickname: 'ritika',
    gender: 'female',
    photo: '/img/girl-1.png',
    dob: '12/11/2000',
    dod: '',
    events: [],
    partner: null
  },
  'kavya.kumbhat': {
    id: 'kavya.kumbhat',
    firstName: 'kavya',
    lastName: 'kumbhat',
    parentId: 'surbhi.kumbhat',
    nickname: 'nannu',
    gender: 'female',
    photo: '/img/kavya.kumbhat.jpeg',
    dob: '11/10/2006',
    dod: '',
    events: [],
    partner: null
  },
  'rishabh.tatia': {
    id: 'rishabh.tatia',
    firstName: 'rishabh',
    lastName: 'tatia',
    parentId: 'rakesh.tatia',
    nickname: 'rishu',
    gender: 'male',
    photo: '/img/rishabh.tatia.jpeg',
    video: '/vid/rishabh.tatia.animated.mp4',
    dob: '01/03/2001',
    dod: '',
    events: [
      {
        date: '05/14/2022',
        title: 'Graduated from Texas A&M University'
      }
    ],
    partner: null
  },
  'arihant.tatia': {
    id: 'arihant.tatia',
    firstName: 'arihant',
    lastName: 'tatia',
    parentId: 'abhishek.tatia',
    nickname: 'nannu',
    gender: 'male',
    photo: '/img/arihant.tatia.jpeg',
    dob: '12/31/2008',
    dod: '',
    events: [],
    partner: null
  },
  'akshat.tatia': {
    id: 'akshat.tatia',
    firstName: 'akshat',
    lastName: 'tatia',
    parentId: 'akhil.tatia',
    nickname: 'akshu',
    gender: 'male',
    photo: '/img/guy-1.png',
    dob: '02/10/2014',
    dod: '',
    events: [],
    partner: null
  },
  'navya.tatia': {
    id: 'navya.tatia',
    firstName: 'navya',
    lastName: 'tatia',
    parentId: 'akhil.tatia',
    nickname: 'navya',
    gender: 'female',
    photo: '/img/navya.tatia.jpeg',
    dob: '08/02/2017',
    dod: '',
    events: [],
    partner: null
  },
  'parth.tatia': {
    id: 'parth.tatia',
    firstName: 'parth',
    lastName: 'tatia',
    parentId: 'nikhil.tatia',
    nickname: 'parth',
    gender: 'male',
    photo: '/img/parth.tatia.jpeg',
    dob: '08/18/2014',
    dod: '',
    events: [],
    partner: null
  },
  'advay.jain': {
    id: 'advay.jain',
    firstName: 'advay',
    lastName: 'jain',
    parentId: 'swati.jain',
    nickname: 'advay',
    gender: 'male',
    photo: '/img/guy-1.png',
    dob: '02/14/2015',
    dod: '',
    events: [],
    partner: null
  },
  'prabhir.jain': {
    id: 'prabhir.jain',
    firstName: 'prabhir',
    lastName: 'jain',
    parentId: 'rini.jain',
    nickname: 'prabhir',
    gender: 'male',
    photo: '/img/prabhir.jain.jpeg',
    dob: '07/26/2020',
    dod: '',
    events: [],
    partner: null
  },
  'arham.tatia': {
    id: 'arham.tatia',
    firstName: 'arham',
    lastName: 'tatia',
    parentId: 'abhishek.tatia',
    nickname: 'arham',
    gender: 'male',
    photo: '/img/guy-1.png',
    dob: '06/25/2008',
    dod: '',
    events: [],
    partner: null
  },
  'anvi.bhandari': {
    id: 'anvi.bhandari',
    firstName: 'anvi',
    lastName: 'bhandari',
    parentId: 'aayushi.bhandari',
    nickname: 'anvi',
    gender: 'female',
    photo: '/img/anvi.bhandari.jpeg',
    dob: '08/16/2015',
    dod: '',
    events: [],
    partner: null
  },
  'mishti.tatia': {
    id: 'mishti.tatia',
    firstName: 'mishti',
    lastName: 'tatia',
    parentId: 'amit.tatia',
    nickname: 'mishti',
    gender: 'female',
    photo: '/img/mishti.tatia.jpeg',
    dob: '07/19/2014',
    dod: '',
    events: [],
    partner: null
  },
  'shiney.tatia': {
    id: 'shiney.tatia',
    firstName: 'shiney',
    lastName: 'tatia',
    parentId: 'amit.tatia',
    nickname: 'shiney',
    gender: 'female',
    photo: '/img/shiney.tatia.jpeg',
    dob: '03/07/2020',
    dod: '',
    events: [],
    partner: null
  }
};
