export const family = {
  'jaswant.tatia': {
    id: 'jaswant.tatia',
    firstName: 'jaswant',
    lastName: 'tatia',
    parentId: null,
    nickname: 'jaswant',
    gender: 'male',
    photo: 'https://monstar-lab.com/global/wp-content/uploads/sites/11/2019/04/male-placeholder-image.jpeg',
    dob: '01/01/1920',
    dod: '01/01/2000',
    events: [],
    partner: {
      id: 'sardar.tatia',
      partnerOf: 'jaswant.tatia',
      marriage_date: '01/01/1945',
      firstName: 'sardar',
      lastName: 'kanwar',
      parentId: null,
      nickname: 'sardar',
      gender: 'female',
      photo: 'https://media.istockphoto.com/vectors/person-gray-photo-placeholder-woman-vector-id1133765698?k=20&m=1133765698&s=612x612&w=0&h=BeJN5JdlWN70OZQeM_jjnj7uPnHPb1ssMNziNs2h7Is=',
      dob: '01/01/1925',
      dod: '01/01/2020',
      events: [],
      children: ['dalpat.tatia', 'prithvi.tatia', 'vimala.bhansali', 'prakash.tatia', 'rajesh.tatia', 'ashok.tatia', 'umesh.tatia']
    }
  },
  'dalpat.tatia': {
    id: 'dalpat.tatia',
    firstName: 'dalpat Raj',
    lastName: 'tatia',
    parentId: 'jaswant.tatia',
    nickname: 'dalpat',
    gender: 'male',
    photo: 'https://monstar-lab.com/global/wp-content/uploads/sites/11/2019/04/male-placeholder-image.jpeg',
    dob: '01/01/1950',
    dod: '01/01/2011',
    events: [],
    partner: {
      id: 'kanchan.tatia',
      partnerOf: 'dalpat.tatia',
      marriage_date: '01/01/1945',
      firstName: 'kanchan',
      lastName: 'tatia',
      parentId: null,
      nickname: 'kanchan',
      gender: 'female',
      photo: 'https://media.istockphoto.com/vectors/person-gray-photo-placeholder-woman-vector-id1133765698?k=20&m=1133765698&s=612x612&w=0&h=BeJN5JdlWN70OZQeM_jjnj7uPnHPb1ssMNziNs2h7Is=',
      dob: '01/01/1953',
      dod: '01/01/2011',
      events: [],
      children: ['reena.kothari', 'nikky.tater', 'surbhi.kumbhat']
    }
  },
  'prithvi.tatia': {
    id: 'prithvi.tatia',
    firstName: 'prithvi Raj',
    lastName: 'tatia',
    parentId: 'jaswant.tatia',
    nickname: 'pimu',
    gender: 'male',
    photo: 'https://monstar-lab.com/global/wp-content/uploads/sites/11/2019/04/male-placeholder-image.jpeg',
    dob: '01/01/1950',
    dod: '01/01/2011',
    events: [],
    partner: {
      id: 'shashi.tatia',
      partnerOf: 'prithvi.tatia',
      marriage_date: '01/01/1945',
      firstName: 'shashi',
      lastName: 'tatia',
      parentId: null,
      nickname: 'shashi',
      gender: 'female',
      photo: 'https://media.istockphoto.com/vectors/person-gray-photo-placeholder-woman-vector-id1133765698?k=20&m=1133765698&s=612x612&w=0&h=BeJN5JdlWN70OZQeM_jjnj7uPnHPb1ssMNziNs2h7Is=',
      dob: '01/01/1953',
      dod: '01/01/2011',
      events: [],
      children: ['rakesh.tatia', 'sumeet.tatia']
    }
  },
  'vimala.bhansali': {
    id: 'vimala.bhansali',
    firstName: 'vimala',
    lastName: 'bhansali',
    parentId: 'jaswant.tatia',
    nickname: 'vimala',
    gender: 'female',
    photo: 'https://media.istockphoto.com/vectors/person-gray-photo-placeholder-woman-vector-id1133765698?k=20&m=1133765698&s=612x612&w=0&h=BeJN5JdlWN70OZQeM_jjnj7uPnHPb1ssMNziNs2h7Is=',
    dob: '01/01/1955',
    dod: '',
    events: [],
    partner: {
      id: 'jagdish.bhansali',
      partnerOf: 'vimala.bhansali',
      marriage_date: '01/01/1975',
      firstName: 'jagdish',
      lastName: 'tatia',
      parentId: null,
      nickname: 'jagdish',
      gender: 'male',
      photo: 'https://monstar-lab.com/global/wp-content/uploads/sites/11/2019/04/male-placeholder-image.jpeg',
      dob: '01/01/1958',
      dod: '',
      events: [],
      children: ['piyush.bhansali', 'priyanka.singhvi']
    }
  },
  'prakash.tatia': {
    id: 'prakash.tatia',
    firstName: 'prakash',
    lastName: 'tatia',
    parentId: 'jaswant.tatia',
    nickname: 'daddy',
    gender: 'male',
    photo: 'https://monstar-lab.com/global/wp-content/uploads/sites/11/2019/04/male-placeholder-image.jpeg',
    dob: '01/01/1955',
    dod: '',
    events: [],
    partner: {
      id: 'chandrakala.tatia',
      partnerOf: 'prakash.tatia',
      marriage_date: '01/01/1975',
      firstName: 'chandrakala',
      lastName: 'tatia',
      parentId: null,
      nickname: 'chandu',
      gender: 'female',
      photo: 'https://media.istockphoto.com/vectors/person-gray-photo-placeholder-woman-vector-id1133765698?k=20&m=1133765698&s=612x612&w=0&h=BeJN5JdlWN70OZQeM_jjnj7uPnHPb1ssMNziNs2h7Is=',
      dob: '01/01/1958',
      dod: '',
      events: [],
      children: ['abhishek.tatia', 'aayushi.bhandari', 'amit.tatia']
    }
  },
  'umesh.tatia': {
    id: 'umesh.tatia',
    firstName: 'umesh',
    lastName: 'tatia',
    parentId: 'jaswant.tatia',
    nickname: 'tepu',
    gender: 'male',
    photo: 'https://monstar-lab.com/global/wp-content/uploads/sites/11/2019/04/male-placeholder-image.jpeg',
    dob: '01/01/1955',
    dod: '',
    events: [],
    partner: {
      id: 'renu.tatia',
      partnerOf: 'umesh.tatia',
      marriage_date: '01/01/1975',
      firstName: 'renu',
      lastName: 'tatia',
      parentId: null,
      nickname: 'renu',
      gender: 'female',
      photo: 'https://media.istockphoto.com/vectors/person-gray-photo-placeholder-woman-vector-id1133765698?k=20&m=1133765698&s=612x612&w=0&h=BeJN5JdlWN70OZQeM_jjnj7uPnHPb1ssMNziNs2h7Is=',
      dob: '01/01/1958',
      dod: '',
      events: [],
      children: ['rini.jain', 'monika.kachawa']
    }
  },
  'ashok.tatia': {
    id: 'ashok.tatia',
    firstName: 'ashok',
    lastName: 'tatia',
    parentId: 'jaswant.tatia',
    nickname: 'sathu',
    gender: 'male',
    photo: 'https://monstar-lab.com/global/wp-content/uploads/sites/11/2019/04/male-placeholder-image.jpeg',
    dob: '01/01/1955',
    dod: '',
    events: [],
    partner: {
      id: 'neelu.tatia',
      partnerOf: 'ashok.tatia',
      marriage_date: '01/01/1975',
      firstName: 'neelu',
      lastName: 'tatia',
      parentId: null,
      nickname: 'neelu',
      gender: 'female',
      photo: 'https://media.istockphoto.com/vectors/person-gray-photo-placeholder-woman-vector-id1133765698?k=20&m=1133765698&s=612x612&w=0&h=BeJN5JdlWN70OZQeM_jjnj7uPnHPb1ssMNziNs2h7Is=',
      dob: '01/01/1958',
      dod: '',
      events: [],
      children: ['swati.jain', 'megha.tatia']
    }
  },
  'rajesh.tatia': {
    id: 'rajesh.tatia',
    firstName: 'rajesh',
    lastName: 'tatia',
    parentId: 'jaswant.tatia',
    nickname: 'raju',
    gender: 'male',
    photo: 'https://monstar-lab.com/global/wp-content/uploads/sites/11/2019/04/male-placeholder-image.jpeg',
    dob: '01/01/1955',
    dod: '',
    events: [],
    partner: {
      id: 'asha.tatia',
      partnerOf: 'rajesh.tatia',
      marriage_date: '01/01/1975',
      firstName: 'asha',
      lastName: 'tatia',
      parentId: null,
      nickname: 'asha',
      gender: 'female',
      photo: 'https://media.istockphoto.com/vectors/person-gray-photo-placeholder-woman-vector-id1133765698?k=20&m=1133765698&s=612x612&w=0&h=BeJN5JdlWN70OZQeM_jjnj7uPnHPb1ssMNziNs2h7Is=',
      dob: '01/01/1958',
      dod: '',
      events: [],
      children: ['akhil.tatia', 'nikhil.tatia']
    }
  },
  'rini.jain': {
    id: 'rini.jain',
    firstName: 'rini',
    lastName: 'jain',
    parentId: 'umesh.tatia',
    nickname: 'bolly',
    gender: 'female',
    photo: 'https://media.istockphoto.com/vectors/person-gray-photo-placeholder-woman-vector-id1133765698?k=20&m=1133765698&s=612x612&w=0&h=BeJN5JdlWN70OZQeM_jjnj7uPnHPb1ssMNziNs2h7Is=',
    dob: '06/20/1972',
    dod: '',
    events: [],
    partner: {
      id: 'piyush.jain',
      partnerOf: 'rini.jain',
      marriage_date: '12/14/1997',
      firstName: 'piyush',
      lastName: 'jain',
      parentId: null,
      nickname: 'piyush',
      gender: 'male',
      photo: 'https://monstar-lab.com/global/wp-content/uploads/sites/11/2019/04/male-placeholder-image.jpeg',
      dob: '10/05/1974',
      dod: '',
      events: [],
      children: []
    }
  },
  'monika.kachawa': {
    id: 'monika.kachawa',
    firstName: 'monika',
    lastName: 'kachawa',
    parentId: 'umesh.tatia',
    nickname: 'bolly',
    gender: 'female',
    photo: 'https://media.istockphoto.com/vectors/person-gray-photo-placeholder-woman-vector-id1133765698?k=20&m=1133765698&s=612x612&w=0&h=BeJN5JdlWN70OZQeM_jjnj7uPnHPb1ssMNziNs2h7Is=',
    dob: '06/20/1972',
    dod: '',
    events: [],
    partner: {
      id: 'varun.kachawa',
      partnerOf: 'monika.kachawa',
      marriage_date: '12/14/1997',
      firstName: 'varun',
      lastName: 'kachawa',
      parentId: null,
      nickname: 'varun',
      gender: 'male',
      photo: 'https://monstar-lab.com/global/wp-content/uploads/sites/11/2019/04/male-placeholder-image.jpeg',
      dob: '10/05/1974',
      dod: '',
      events: [],
      children: []
    }
  },
  'swati.jain': {
    id: 'swati.jain',
    firstName: 'swati',
    lastName: 'jain',
    parentId: 'ashok.tatia',
    nickname: 'archi',
    gender: 'female',
    photo: 'https://media.istockphoto.com/vectors/person-gray-photo-placeholder-woman-vector-id1133765698?k=20&m=1133765698&s=612x612&w=0&h=BeJN5JdlWN70OZQeM_jjnj7uPnHPb1ssMNziNs2h7Is=',
    dob: '06/20/1972',
    dod: '',
    events: [],
    partner: {
      id: 'vishal.jain',
      partnerOf: 'swati.jain',
      marriage_date: '12/14/1997',
      firstName: 'vishal',
      lastName: 'jain',
      parentId: null,
      nickname: 'vishal',
      gender: 'male',
      photo: 'https://monstar-lab.com/global/wp-content/uploads/sites/11/2019/04/male-placeholder-image.jpeg',
      dob: '10/05/1974',
      dod: '',
      events: [],
      children: []
    }
  },
  'megha.tatia': {
    id: 'megha.tatia',
    firstName: 'megha',
    lastName: 'tatia',
    parentId: 'ashok.tatia',
    nickname: 'guddu',
    gender: 'female',
    photo: 'https://media.istockphoto.com/vectors/person-gray-photo-placeholder-woman-vector-id1133765698?k=20&m=1133765698&s=612x612&w=0&h=BeJN5JdlWN70OZQeM_jjnj7uPnHPb1ssMNziNs2h7Is=',
    dob: '06/20/1972',
    dod: '',
    events: [],
    partner: null
  },
  'akhil.tatia': {
    id: 'akhil.tatia',
    firstName: 'akhil',
    lastName: 'tatia',
    parentId: 'rajesh.tatia',
    nickname: 'akhil',
    gender: 'male',
    photo: 'https://monstar-lab.com/global/wp-content/uploads/sites/11/2019/04/male-placeholder-image.jpeg',
    dob: '06/20/1972',
    dod: '',
    events: [],
    partner: {
      id: 'kritika.tatia',
      partnerOf: 'akhil.tatia',
      marriage_date: '12/14/1997',
      firstName: 'kritika',
      lastName: 'tatia',
      parentId: null,
      nickname: 'kritika',
      gender: 'female',
      photo: 'https://media.istockphoto.com/vectors/person-gray-photo-placeholder-woman-vector-id1133765698?k=20&m=1133765698&s=612x612&w=0&h=BeJN5JdlWN70OZQeM_jjnj7uPnHPb1ssMNziNs2h7Is=',
      dob: '10/05/1974',
      dod: '',
      events: [],
      children: ['akshat.tatia']
    }
  },
  'nikhil.tatia': {
    id: 'nikhil.tatia',
    firstName: 'nikhil',
    lastName: 'tatia',
    parentId: 'rajesh.tatia',
    nickname: 'nikhil',
    gender: 'male',
    photo: 'https://monstar-lab.com/global/wp-content/uploads/sites/11/2019/04/male-placeholder-image.jpeg',
    dob: '06/20/1972',
    dod: '',
    events: [],
    partner: {
      id: 'ankita.tatia',
      partnerOf: 'nikhil.tatia',
      marriage_date: '12/14/1997',
      firstName: 'ankita',
      lastName: 'tatia',
      parentId: null,
      nickname: 'ankita',
      gender: 'female',
      photo: 'https://media.istockphoto.com/vectors/person-gray-photo-placeholder-woman-vector-id1133765698?k=20&m=1133765698&s=612x612&w=0&h=BeJN5JdlWN70OZQeM_jjnj7uPnHPb1ssMNziNs2h7Is=',
      dob: '10/05/1974',
      dod: '',
      events: [],
      children: []
    }
  },
  'rakesh.tatia': {
    id: 'rakesh.tatia',
    firstName: 'rakesh',
    lastName: 'tatia',
    parentId: 'prithvi.tatia',
    nickname: 'riku',
    gender: 'male',
    photo: 'https://monstar-lab.com/global/wp-content/uploads/sites/11/2019/04/male-placeholder-image.jpeg',
    dob: '06/20/1972',
    dod: '',
    events: [],
    partner: {
      id: 'prerna.tatia',
      partnerOf: 'rakesh.tatia',
      marriage_date: '12/14/1997',
      firstName: 'prerna',
      lastName: 'tatia',
      parentId: null,
      nickname: 'prerna',
      gender: 'female',
      photo: 'https://media.istockphoto.com/vectors/person-gray-photo-placeholder-woman-vector-id1133765698?k=20&m=1133765698&s=612x612&w=0&h=BeJN5JdlWN70OZQeM_jjnj7uPnHPb1ssMNziNs2h7Is=',
      dob: '10/05/1974',
      dod: '',
      events: [],
      children: ['rishabh.tatia']
    }
  },
  'piyush.bhansali': {
    id: 'piyush.bhansali',
    firstName: 'piyush',
    lastName: 'bhansali',
    parentId: 'vimala.bhansali',
    nickname: 'prince',
    gender: 'male',
    photo: 'https://monstar-lab.com/global/wp-content/uploads/sites/11/2019/04/male-placeholder-image.jpeg',
    dob: '06/20/1972',
    dod: '',
    events: [],
    partner: {
      id: 'vanita.bhansali',
      partnerOf: 'piyush.bhansali',
      marriage_date: '12/14/1997',
      firstName: 'vanita',
      lastName: 'bhansali',
      parentId: null,
      nickname: 'vanita',
      gender: 'female',
      photo: 'https://media.istockphoto.com/vectors/person-gray-photo-placeholder-woman-vector-id1133765698?k=20&m=1133765698&s=612x612&w=0&h=BeJN5JdlWN70OZQeM_jjnj7uPnHPb1ssMNziNs2h7Is=',
      dob: '10/05/1974',
      dod: '',
      events: [],
      children: ['priyanshi.bhansali', 'mahek.bhansali']
    }
  },
  'priyanka.singhvi': {
    id: 'priyanka.singhvi',
    firstName: 'priyanka',
    lastName: 'singhvi',
    parentId: 'vimala.bhansali',
    nickname: 'pinky',
    gender: 'female',
    photo: 'https://media.istockphoto.com/vectors/person-gray-photo-placeholder-woman-vector-id1133765698?k=20&m=1133765698&s=612x612&w=0&h=BeJN5JdlWN70OZQeM_jjnj7uPnHPb1ssMNziNs2h7Is=',
    dob: '06/20/1972',
    dod: '',
    events: [],
    partner: {
      id: 'rupesh.singhvi',
      partnerOf: 'priyanka.singhvi',
      marriage_date: '12/14/1997',
      firstName: 'rupesh',
      lastName: 'singhvi',
      parentId: null,
      nickname: 'rupesh',
      gender: 'male',
      photo: 'https://monstar-lab.com/global/wp-content/uploads/sites/11/2019/04/male-placeholder-image.jpeg',
      dob: '10/05/1974',
      dod: '',
      events: [],
      children: ['neelay.singhvi', 'rakshiti.singhvi']
    }
  },
  'reena.kothari': {
    id: 'reena.kothari',
    firstName: 'reena',
    lastName: 'tatia',
    parentId: 'dalpat.tatia',
    nickname: 'reena',
    gender: 'female',
    photo: 'https://media.istockphoto.com/vectors/person-gray-photo-placeholder-woman-vector-id1133765698?k=20&m=1133765698&s=612x612&w=0&h=BeJN5JdlWN70OZQeM_jjnj7uPnHPb1ssMNziNs2h7Is=',
    dob: '06/20/1972',
    dod: '',
    events: [],
    partner: {
      id: 'nirmal.kothari',
      partnerOf: 'reena.kothari',
      marriage_date: '12/14/1997',
      firstName: 'nirmal',
      lastName: 'kothari',
      parentId: null,
      nickname: 'nirmal',
      gender: 'male',
      photo: 'https://monstar-lab.com/global/wp-content/uploads/sites/11/2019/04/male-placeholder-image.jpeg',
      dob: '10/05/1974',
      dod: '',
      events: [],
      children: ['juhi.mehta', 'shaily.kothari', 'pragya.kothari']
    }
  },
  'nikky.tater': {
    id: 'nikky.tater',
    firstName: 'nikki',
    lastName: 'tater',
    parentId: 'dalpat.tatia',
    nickname: 'nikki',
    gender: 'female',
    photo: 'https://media.istockphoto.com/vectors/person-gray-photo-placeholder-woman-vector-id1133765698?k=20&m=1133765698&s=612x612&w=0&h=BeJN5JdlWN70OZQeM_jjnj7uPnHPb1ssMNziNs2h7Is=',
    dob: '06/20/1972',
    dod: '',
    events: [],
    partner: {
      id: 'sanjay.tatia',
      partnerOf: 'nikky.tater',
      marriage_date: '12/14/1997',
      firstName: 'sanjay',
      lastName: 'tater',
      parentId: null,
      nickname: 'sanjay',
      gender: 'male',
      photo: 'https://monstar-lab.com/global/wp-content/uploads/sites/11/2019/04/male-placeholder-image.jpeg',
      dob: '10/05/1974',
      dod: '',
      events: [],
      children: ['isha.tater', 'aryan.tater']
    }
  },
  'surbhi.kumbhat': {
    id: 'surbhi.kumbhat',
    firstName: 'surbhi',
    lastName: 'tatia',
    parentId: 'dalpat.tatia',
    nickname: 'surbhi',
    gender: 'female',
    photo: 'https://media.istockphoto.com/vectors/person-gray-photo-placeholder-woman-vector-id1133765698?k=20&m=1133765698&s=612x612&w=0&h=BeJN5JdlWN70OZQeM_jjnj7uPnHPb1ssMNziNs2h7Is=',
    dob: '06/20/1972',
    dod: '',
    events: [],
    partner: {
      id: 'neeraj.kumbhat',
      partnerOf: 'surbhi.kumbhat',
      marriage_date: '12/14/1997',
      firstName: 'neeraj',
      lastName: 'tatia',
      parentId: null,
      nickname: 'neeraj',
      gender: 'male',
      photo: 'https://monstar-lab.com/global/wp-content/uploads/sites/11/2019/04/male-placeholder-image.jpeg',
      dob: '10/05/1974',
      dod: '',
      events: [],
      children: ['ritika.kumbhat', 'kavya.kumbhat']
    }
  },
  'abhishek.tatia': {
    id: 'abhishek.tatia',
    firstName: 'abhishek',
    lastName: 'tatia',
    parentId: 'prakash.tatia',
    nickname: 'betu',
    gender: 'male',
    photo: 'https://monstar-lab.com/global/wp-content/uploads/sites/11/2019/04/male-placeholder-image.jpeg',
    dob: '06/20/1972',
    dod: '',
    events: [],
    partner: {
      id: 'anjali.tatia',
      partnerOf: 'abhishek.tatia',
      marriage_date: '12/14/1997',
      firstName: 'anjali',
      lastName: 'tatia',
      parentId: null,
      nickname: 'anjali',
      gender: 'female',
      photo: 'https://media.istockphoto.com/vectors/person-gray-photo-placeholder-woman-vector-id1133765698?k=20&m=1133765698&s=612x612&w=0&h=BeJN5JdlWN70OZQeM_jjnj7uPnHPb1ssMNziNs2h7Is=',
      dob: '10/05/1974',
      dod: '',
      events: [],
      children: ['arihant.tatia', 'arham.tatia']
    }
  },
  'aayushi.bhandari': {
    id: 'aayushi.bhandari',
    firstName: 'anu',
    lastName: 'bhandari',
    parentId: 'prakash.tatia',
    nickname: 'anu',
    gender: 'female',
    photo: 'https://media.istockphoto.com/vectors/person-gray-photo-placeholder-woman-vector-id1133765698?k=20&m=1133765698&s=612x612&w=0&h=BeJN5JdlWN70OZQeM_jjnj7uPnHPb1ssMNziNs2h7Is=',
    dob: '06/20/1972',
    dod: '',
    events: [],
    partner: {
      id: 'saurav.bhandari',
      partnerOf: 'aayushi.bhandari',
      marriage_date: '12/14/1997',
      firstName: 'saurav',
      lastName: 'bhandari',
      parentId: null,
      nickname: 'saurav',
      gender: 'male',
      photo: 'https://monstar-lab.com/global/wp-content/uploads/sites/11/2019/04/male-placeholder-image.jpeg',
      dob: '10/05/1974',
      dod: '',
      events: [],
      children: ['anvi.bhandari']
    }
  },
  'amit.tatia': {
    id: 'amit.tatia',
    firstName: 'amit',
    lastName: 'tatia',
    parentId: 'prakash.tatia',
    nickname: 'sharad',
    gender: 'male',
    photo: 'https://monstar-lab.com/global/wp-content/uploads/sites/11/2019/04/male-placeholder-image.jpeg',
    dob: '06/20/1972',
    dod: '',
    events: [],
    partner: {
      id: 'richa.tatia',
      partnerOf: 'amit.tatia',
      marriage_date: '12/14/1997',
      firstName: 'richa',
      lastName: 'tatia',
      parentId: null,
      nickname: 'richa',
      gender: 'female',
      photo: 'https://media.istockphoto.com/vectors/person-gray-photo-placeholder-woman-vector-id1133765698?k=20&m=1133765698&s=612x612&w=0&h=BeJN5JdlWN70OZQeM_jjnj7uPnHPb1ssMNziNs2h7Is=',
      dob: '10/05/1974',
      dod: '',
      events: [],
      children: ['mishti.tatia']
    }
  },
  'sumeet.tatia': {
    id: 'sumeet.tatia',
    firstName: 'sumeet',
    lastName: 'tatia',
    parentId: 'prithvi.tatia',
    nickname: 'chiku',
    gender: 'male',
    photo: 'https://monstar-lab.com/global/wp-content/uploads/sites/11/2019/04/male-placeholder-image.jpeg',
    dob: '04/03/1974',
    dod: '01/01/1992',
    events: [],
    partner: null
  },
  'juhi.mehta': {
    id: 'juhi.mehta',
    firstName: 'juhi',
    lastName: 'mehta',
    parentId: 'reena.kothari',
    nickname: 'juhi',
    gender: 'female',
    photo: 'https://media.istockphoto.com/vectors/person-gray-photo-placeholder-woman-vector-id1133765698?k=20&m=1133765698&s=612x612&w=0&h=BeJN5JdlWN70OZQeM_jjnj7uPnHPb1ssMNziNs2h7Is=',
    dob: '01/03/2001',
    dod: '',
    events: [],
    partner: {
      id: 'siddharth.mehta',
      partnerOf: 'juhi.mehta',
      marriage_date: '12/14/1997',
      firstName: 'siddharth',
      lastName: 'mehta',
      parentId: null,
      nickname: 'siddharth',
      gender: 'male',
      photo: 'https://monstar-lab.com/global/wp-content/uploads/sites/11/2019/04/male-placeholder-image.jpeg',
      dob: '10/05/1974',
      dod: '',
      events: [],
      children: []
    }
  },
  'shaily.kothari': {
    id: 'shaily.kothari',
    firstName: 'sonu',
    lastName: 'kothari',
    parentId: 'reena.kothari',
    nickname: 'sonu',
    gender: 'female',
    photo: 'https://media.istockphoto.com/vectors/person-gray-photo-placeholder-woman-vector-id1133765698?k=20&m=1133765698&s=612x612&w=0&h=BeJN5JdlWN70OZQeM_jjnj7uPnHPb1ssMNziNs2h7Is=',
    dob: '01/03/2001',
    dod: '',
    events: [],
    partner: null
  },
  'pragya.kothari': {
    id: 'pragya.kothari',
    firstName: 'pragya',
    lastName: 'kothari',
    parentId: 'reena.kothari',
    nickname: 'pragy',
    gender: 'male',
    photo: 'https://monstar-lab.com/global/wp-content/uploads/sites/11/2019/04/male-placeholder-image.jpeg',
    dob: '01/03/2001',
    dod: '',
    events: [],
    partner: null
  },
  'neelay.singhvi': {
    id: 'neelay.singhvi',
    firstName: 'neelay',
    lastName: 'singhvi',
    parentId: 'priyanka.singhvi',
    nickname: 'neelay',
    gender: 'male',
    photo: 'https://monstar-lab.com/global/wp-content/uploads/sites/11/2019/04/male-placeholder-image.jpeg',
    dob: '01/03/2001',
    dod: '',
    events: [],
    partner: null
  },
  'rakshiti.singhvi': {
    id: 'rakshiti.singhvi',
    firstName: 'rakshiti',
    lastName: 'singhvi',
    parentId: 'priyanka.singhvi',
    nickname: 'bebo',
    gender: 'female',
    photo: 'https://media.istockphoto.com/vectors/person-gray-photo-placeholder-woman-vector-id1133765698?k=20&m=1133765698&s=612x612&w=0&h=BeJN5JdlWN70OZQeM_jjnj7uPnHPb1ssMNziNs2h7Is=',
    dob: '01/03/2001',
    dod: '',
    events: [],
    partner: null
  },
  'priyanshi.bhansali': {
    id: 'priyanshi.bhansali',
    firstName: 'priyanshi',
    lastName: 'bhansali',
    parentId: 'piyush.bhansali',
    nickname: 'priyanshi',
    gender: 'female',
    photo: 'https://media.istockphoto.com/vectors/person-gray-photo-placeholder-woman-vector-id1133765698?k=20&m=1133765698&s=612x612&w=0&h=BeJN5JdlWN70OZQeM_jjnj7uPnHPb1ssMNziNs2h7Is=',
    dob: '01/03/2001',
    dod: '',
    events: [],
    partner: null
  },
  'mahek.bhansali': {
    id: 'mahek.bhansali',
    firstName: 'mahek',
    lastName: 'bhansali',
    parentId: 'piyush.bhansali',
    nickname: 'mahek',
    gender: 'female',
    photo: 'https://media.istockphoto.com/vectors/person-gray-photo-placeholder-woman-vector-id1133765698?k=20&m=1133765698&s=612x612&w=0&h=BeJN5JdlWN70OZQeM_jjnj7uPnHPb1ssMNziNs2h7Is=',
    dob: '01/03/2001',
    dod: '',
    events: [],
    partner: null
  },
  'isha.tater': {
    id: 'isha.tater',
    firstName: 'isha',
    lastName: 'tater',
    parentId: 'nikky.tater',
    nickname: 'guddu',
    gender: 'female',
    photo: 'https://media.istockphoto.com/vectors/person-gray-photo-placeholder-woman-vector-id1133765698?k=20&m=1133765698&s=612x612&w=0&h=BeJN5JdlWN70OZQeM_jjnj7uPnHPb1ssMNziNs2h7Is=',
    dob: '01/03/2001',
    dod: '',
    events: [],
    partner: null
  },
  'aryan.tater': {
    id: 'aryan.tater',
    firstName: 'aryan',
    lastName: 'tater',
    parentId: 'nikky.tater',
    nickname: 'aru',
    gender: 'male',
    photo: 'https://monstar-lab.com/global/wp-content/uploads/sites/11/2019/04/male-placeholder-image.jpeg',
    dob: '01/03/2001',
    dod: '',
    events: [],
    partner: null
  },
  'ritika.kumbhat': {
    id: 'ritika.kumbhat',
    firstName: 'ritika',
    lastName: 'kumbhat',
    parentId: 'surbhi.kumbhat',
    nickname: 'ritika',
    gender: 'female',
    photo: 'https://media.istockphoto.com/vectors/person-gray-photo-placeholder-woman-vector-id1133765698?k=20&m=1133765698&s=612x612&w=0&h=BeJN5JdlWN70OZQeM_jjnj7uPnHPb1ssMNziNs2h7Is=',
    dob: '01/03/2001',
    dod: '',
    events: [],
    partner: null
  },
  'kavya.kumbhat': {
    id: 'kavya.kumbhat',
    firstName: 'kavya',
    lastName: 'kumbhat',
    parentId: 'surbhi.kumbhat',
    nickname: 'nannu',
    gender: 'female',
    photo: 'https://media.istockphoto.com/vectors/person-gray-photo-placeholder-woman-vector-id1133765698?k=20&m=1133765698&s=612x612&w=0&h=BeJN5JdlWN70OZQeM_jjnj7uPnHPb1ssMNziNs2h7Is=',
    dob: '01/03/2001',
    dod: '',
    events: [],
    partner: null
  },
  'rishabh.tatia': {
    id: 'rishabh.tatia',
    firstName: 'rishabh',
    lastName: 'tatia',
    parentId: 'rakesh.tatia',
    nickname: 'rishu',
    gender: 'male',
    photo: 'https://monstar-lab.com/global/wp-content/uploads/sites/11/2019/04/male-placeholder-image.jpeg',
    dob: '01/03/2001',
    dod: '',
    events: [
      {
        date: '05/14/2022',
        title: 'Graduated from Texas A&M University'
      }
    ],
    partner: null
  },
  'arihant.tatia': {
    id: 'arihant.tatia',
    firstName: 'arihant',
    lastName: 'tatia',
    parentId: 'abhishek.tatia',
    nickname: 'nannu',
    gender: 'male',
    photo: 'https://monstar-lab.com/global/wp-content/uploads/sites/11/2019/04/male-placeholder-image.jpeg',
    dob: '01/03/2001',
    dod: '',
    events: [],
    partner: null
  },
  'akshat.tatia': {
    id: 'akshat.tatia',
    firstName: 'akshat',
    lastName: 'tatia',
    parentId: 'akhil.tatia',
    nickname: 'akshu',
    gender: 'male',
    photo: 'https://monstar-lab.com/global/wp-content/uploads/sites/11/2019/04/male-placeholder-image.jpeg',
    dob: '01/03/2001',
    dod: '',
    events: [],
    partner: null
  },
  'parth.tatia': {
    id: 'parth.tatia',
    firstName: 'parth',
    lastName: 'tatia',
    parentId: 'nikhil.tatia',
    nickname: 'parth',
    gender: 'male',
    photo: 'https://monstar-lab.com/global/wp-content/uploads/sites/11/2019/04/male-placeholder-image.jpeg',
    dob: '01/03/2001',
    dod: '',
    events: [],
    partner: null
  },
  'arham.tatia': {
    id: 'arham.tatia',
    firstName: 'arham',
    lastName: 'tatia',
    parentId: 'abhishek.tatia',
    nickname: 'arham',
    gender: 'male',
    photo: 'https://monstar-lab.com/global/wp-content/uploads/sites/11/2019/04/male-placeholder-image.jpeg',
    dob: '01/03/2001',
    dod: '',
    events: [],
    partner: null
  },
  'anvi.bhandari': {
    id: 'anvi.bhandari',
    firstName: 'anvi',
    lastName: 'bhandari',
    parentId: 'aayushi.bhandari',
    nickname: 'anvi',
    gender: 'female',
    photo: 'https://media.istockphoto.com/vectors/person-gray-photo-placeholder-woman-vector-id1133765698?k=20&m=1133765698&s=612x612&w=0&h=BeJN5JdlWN70OZQeM_jjnj7uPnHPb1ssMNziNs2h7Is=',
    dob: '01/03/2001',
    dod: '',
    events: [],
    partner: null
  },
  'mishti.tatia': {
    id: 'mishti.tatia',
    firstName: 'mishti',
    lastName: 'tatia',
    parentId: 'amit.tatia',
    nickname: 'mishti',
    gender: 'female',
    photo: 'https://media.istockphoto.com/vectors/person-gray-photo-placeholder-woman-vector-id1133765698?k=20&m=1133765698&s=612x612&w=0&h=BeJN5JdlWN70OZQeM_jjnj7uPnHPb1ssMNziNs2h7Is=',
    dob: '01/03/2001',
    dod: '',
    events: [],
    partner: null
  }
};
